apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rp
  labels:
    app: myapp-rp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
